Class core.data.Address Extends (%Library.Persistent, core.model.Address)
{

Storage Default
{
<Data name="AddressDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Street</Value>
</Value>
<Value name="3">
<Value>Number</Value>
</Value>
<Value name="4">
<Value>Complement</Value>
</Value>
<Value name="5">
<Value>City</Value>
</Value>
<Value name="6">
<Value>State</Value>
</Value>
<Value name="7">
<Value>Country</Value>
</Value>
<Value name="8">
<Value>PostalCode</Value>
</Value>
<Value name="9">
<Value>CreatedAt</Value>
</Value>
<Value name="10">
<Value>UpdatedAt</Value>
</Value>
<Value name="11">
<Value>DeletedAt</Value>
</Value>
</Data>
<DataLocation>^core.data.AddressD</DataLocation>
<DefaultData>AddressDefaultData</DefaultData>
<IdLocation>^core.data.AddressD</IdLocation>
<IndexLocation>^core.data.AddressI</IndexLocation>
<StreamLocation>^core.data.AddressS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
